// Deutsche Bedeutungs-Namen der 114 Suren (Audit 2026-07-19 B2): die
// AlQuran.cloud-Metadaten liefern die Namensbedeutung nur auf Englisch
// ("The Cow"), was in der deutschen UI als Fremdkörper auffiel. Für andere
// UI-Sprachen ist die englische Bedeutung bzw. der (sprachneutrale)
// transliterierte Name weiterhin der Standard - Türkisch etwa nutzt
// üblicherweise ohnehin die Transliteration (Fâtiha, Bakara), nicht die
// Bedeutungsübersetzung. Namen folgen den im Deutschen etablierten
// Renderings (Bubenheim/Elyas-Umfeld, deutschsprachige Koranliteratur).
const GERMAN_SURAH_NAMES: Record<number, string> = {
  1: 'Die Eröffnung',
  2: 'Die Kuh',
  3: 'Die Familie Imrans',
  4: 'Die Frauen',
  5: 'Der Tisch',
  6: 'Das Vieh',
  7: 'Die Höhen',
  8: 'Die Beute',
  9: 'Die Reue',
  10: 'Yunus (Jona)',
  11: 'Hud',
  12: 'Yusuf (Josef)',
  13: 'Der Donner',
  14: 'Ibrahim (Abraham)',
  15: 'Al-Hidschr',
  16: 'Die Biene',
  17: 'Die Nachtreise',
  18: 'Die Höhle',
  19: 'Maryam (Maria)',
  20: 'Ta-Ha',
  21: 'Die Propheten',
  22: 'Die Pilgerfahrt',
  23: 'Die Gläubigen',
  24: 'Das Licht',
  25: 'Die Unterscheidung',
  26: 'Die Dichter',
  27: 'Die Ameisen',
  28: 'Die Geschichten',
  29: 'Die Spinne',
  30: 'Die Römer',
  31: 'Luqman',
  32: 'Die Niederwerfung',
  33: 'Die Verbündeten',
  34: 'Saba',
  35: 'Der Erschaffer',
  36: 'Ya-Sin',
  37: 'Die sich Reihenden',
  38: 'Sad',
  39: 'Die Scharen',
  40: 'Der Vergebende',
  41: 'Ausführlich dargelegt',
  42: 'Die Beratung',
  43: 'Der Goldschmuck',
  44: 'Der Rauch',
  45: 'Die Kniende',
  46: 'Die Sanddünen',
  47: 'Muhammad',
  48: 'Der Sieg',
  49: 'Die Gemächer',
  50: 'Qaf',
  51: 'Die Aufwirbelnden',
  52: 'Der Berg',
  53: 'Der Stern',
  54: 'Der Mond',
  55: 'Der Allerbarmer',
  56: 'Das eintreffende Ereignis',
  57: 'Das Eisen',
  58: 'Die Streitende',
  59: 'Die Versammlung',
  60: 'Die Geprüfte',
  61: 'Die Reihe',
  62: 'Der Freitag',
  63: 'Die Heuchler',
  64: 'Die Übervorteilung',
  65: 'Die Scheidung',
  66: 'Das Verbot',
  67: 'Die Herrschaft',
  68: 'Die Feder',
  69: 'Die fällig Werdende',
  70: 'Die Aufstiegswege',
  71: 'Nuh (Noah)',
  72: 'Die Dschinn',
  73: 'Der Eingehüllte',
  74: 'Der Zugedeckte',
  75: 'Die Auferstehung',
  76: 'Der Mensch',
  77: 'Die Entsandten',
  78: 'Die Kunde',
  79: 'Die Entreißenden',
  80: 'Er runzelte die Stirn',
  81: 'Das Einrollen',
  82: 'Die Spaltung',
  83: 'Die das Maß Kürzenden',
  84: 'Das Sich-Spalten',
  85: 'Die Sternbilder',
  86: 'Der Nachtstern',
  87: 'Der Allerhöchste',
  88: 'Die Bedeckende',
  89: 'Die Morgendämmerung',
  90: 'Die Stadt',
  91: 'Die Sonne',
  92: 'Die Nacht',
  93: 'Die Morgenhelle',
  94: 'Die Weitung',
  95: 'Die Feige',
  96: 'Der Blutklumpen',
  97: 'Die Bestimmung',
  98: 'Der klare Beweis',
  99: 'Das Erdbeben',
  100: 'Die Galoppierenden',
  101: 'Das Verhängnis',
  102: 'Die Vermehrung',
  103: 'Das Zeitalter',
  104: 'Der Verleumder',
  105: 'Der Elefant',
  106: 'Die Quraisch',
  107: 'Die Hilfeleistung',
  108: 'Der Überfluss',
  109: 'Die Ungläubigen',
  110: 'Die Hilfe',
  111: 'Die Palmfasern',
  112: 'Die Aufrichtigkeit',
  113: 'Der Tagesanbruch',
  114: 'Die Menschen',
};

/**
 * Bedeutungs-Name einer Sure in der UI-Sprache; fällt außerhalb von Deutsch
 * (bzw. bei Lücken) auf die englische Bedeutung aus den API-Metadaten zurück.
 */
export function surahNameTranslation(
  surahNumber: number,
  locale: string,
  englishFallback: string,
): string {
  if (locale === 'de') return GERMAN_SURAH_NAMES[surahNumber] ?? englishFallback;
  return englishFallback;
}
