// Satz-Puzzle: bekannte islamische Sätze/Verse aus gemischten Wörtern in die
// richtige Reihenfolge bringen. Kuratierte, unstrittige Standard-Formeln
// (Basmala, Kalima, Adhkar) — Bedeutungen in 6 Sprachen.

import type { Locale } from '@/lib/locale-detect';

import { shuffle, type Rand } from '../learn/quiz';

export interface PuzzlePhrase {
  id: string;
  /** Wörter in korrekter Reihenfolge (rechts beginnend gelesen). */
  words: string[];
  translit: string;
  /** Bisher nur in den ursprünglichen 6 Sprachen befüllt — die 8 Phase-1-
   * Sprachen (#60) fallen auf Englisch zurück (siehe app/quiz/puzzle.tsx). */
  meaning: Partial<Record<Locale, string>>;
}

export const PUZZLE_PHRASES: PuzzlePhrase[] = [
  {
    id: 'basmala',
    words: ['بِسْمِ', 'اللهِ', 'الرَّحْمَٰنِ', 'الرَّحِيمِ'],
    translit: 'Bismillāhir-raḥmānir-raḥīm',
    meaning: {
      de: 'Im Namen Allahs, des Allerbarmers, des Barmherzigen',
      en: 'In the name of Allah, the Most Gracious, the Most Merciful',
      tr: 'Rahmân ve Rahîm olan Allah’ın adıyla',
      ar: 'افتتاح كل أمر باسم الله',
      es: 'En el nombre de Alá, el Compasivo, el Misericordioso',
      fr: 'Au nom d’Allah, le Tout Miséricordieux, le Très Miséricordieux',
    id: 'Dengan nama Allah Yang Maha Pengasih, Maha Penyayang',
    bn: 'পরম করুণাময় ও অসীম দয়ালু আল্লাহর নামে',
    fa: 'به نام خداوند بخشنده مهربان',
    ms: 'Dengan nama Allah Yang Maha Pemurah lagi Maha Penyayang',
    ur: 'اللہ کے نام سے جو نہایت مہربان، رحم کرنے والا ہے',
    ru: 'Во имя Аллаха, Милостивого, Милосердного',
    sw: 'Kwa jina la Allah Mwingi wa Rehema, Mwenye Kurehemu',
    ps: 'د لوراند او مهربان الله په نوم',
    },
  },
  {
    id: 'hamd',
    words: ['الْحَمْدُ', 'لِلَّهِ', 'رَبِّ', 'الْعَالَمِينَ'],
    translit: 'Al-ḥamdu lillāhi rabbil-ʿālamīn',
    meaning: {
      de: 'Alles Lob gebührt Allah, dem Herrn der Welten',
      en: 'All praise is due to Allah, Lord of the worlds',
      tr: 'Hamd, âlemlerin Rabbi Allah’a mahsustur',
      ar: 'الثناء على الله رب العالمين',
      es: 'Toda alabanza pertenece a Alá, Señor de los mundos',
      fr: 'Louange à Allah, Seigneur des mondes',
    id: 'Segala puji bagi Allah, Tuhan semesta alam',
    bn: 'সমস্ত প্রশংসা আল্লাহর জন্য, যিনি সকল জগতের প্রতিপালক',
    fa: 'همه ستایش از آنِ خداست، پروردگار جهانیان',
    ms: 'Segala puji bagi Allah, Tuhan sekalian alam',
    ur: 'ساری تعریف اللہ کے لیے ہے، جو تمام جہانوں کا رب ہے',
    ru: 'Вся хвала Аллаху, Господу миров',
    sw: 'Sifa zote ni za Allah, Mola wa walimwengu wote',
    ps: 'ټوله ستاینه د الله لپاره ده، د نړیوالو رب',
    },
  },
  {
    id: 'kalima',
    words: ['لَا', 'إِلَٰهَ', 'إِلَّا', 'اللهُ'],
    translit: 'Lā ilāha illallāh',
    meaning: {
      de: 'Es gibt keinen Gott außer Allah',
      en: 'There is no god but Allah',
      tr: 'Allah’tan başka ilah yoktur',
      ar: 'كلمة التوحيد',
      es: 'No hay más dios que Alá',
      fr: 'Il n’y a de divinité qu’Allah',
    id: 'tidak ada tuhan selain Allah',
    bn: 'আল্লাহ ছাড়া কোনো উপাস্য নেই',
    fa: 'هیچ معبودی جز خدا نیست',
    ms: 'tiada tuhan melainkan Allah',
    ur: 'اللہ کے سوا کوئی معبود نہیں',
    ru: 'нет божества, кроме Аллаха',
    sw: 'hakuna mola ila Allah',
    ps: 'له الله پرته بل معبود نشته',
    },
  },
  {
    id: 'rasul',
    words: ['مُحَمَّدٌ', 'رَسُولُ', 'اللهِ'],
    translit: 'Muḥammadur-rasūlullāh',
    meaning: {
      de: 'Muhammad ist der Gesandte Allahs',
      en: 'Muhammad is the Messenger of Allah',
      tr: 'Muhammed, Allah’ın elçisidir',
      ar: 'محمد رسول الله',
      es: 'Muhammad es el Mensajero de Alá',
      fr: 'Muhammad est le Messager d’Allah',
    id: 'Muhammad adalah utusan Allah',
    bn: 'মুহাম্মদ আল্লাহর রাসূল',
    fa: 'محمد فرستادهٔ خداست',
    ms: 'Muhammad adalah utusan Allah',
    ur: 'محمد اللہ کے رسول ہیں',
    ru: 'Мухаммад — посланник Аллаха',
    sw: 'Muhammad ni mtume wa Allah',
    ps: 'محمد د الله استازی دی',
    },
  },
  {
    id: 'tasbih',
    words: ['سُبْحَانَ', 'اللهِ', 'وَبِحَمْدِهِ'],
    translit: 'Subḥānallāhi wa-bi-ḥamdih',
    meaning: {
      de: 'Gepriesen sei Allah und alles Lob gebührt Ihm',
      en: 'Glory be to Allah and praise be to Him',
      tr: 'Allah’ı hamd ile tesbih ederim',
      ar: 'تسبيح الله مع حمده',
      es: 'Gloria a Alá y alabado sea',
      fr: 'Gloire et louange à Allah',
    id: 'Mahasuci Allah dan segala puji bagi-Nya',
    bn: 'আল্লাহ পবিত্র এবং সমস্ত প্রশংসা তাঁরই',
    fa: 'خدا منزه است و ستایش نیز از آنِ اوست',
    ms: 'Maha Suci Allah dan segala puji bagi-Nya',
    ur: 'اللہ پاک ہے اور ساری تعریف اسی کی ہے',
    ru: 'Пречист Аллах, и хвала Ему',
    sw: 'Ametakasika Allah na sifa zote ni Zake',
    ps: 'الله پاک دی او ټوله ستاینه یې ده',
    },
  },
  {
    id: 'istiadha',
    words: ['أَعُوذُ', 'بِاللهِ', 'مِنَ', 'الشَّيْطَانِ', 'الرَّجِيمِ'],
    translit: 'Aʿūdhu billāhi minash-shayṭānir-rajīm',
    meaning: {
      de: 'Ich suche Zuflucht bei Allah vor dem verfluchten Satan',
      en: 'I seek refuge in Allah from the accursed Satan',
      tr: 'Kovulmuş şeytandan Allah’a sığınırım',
      ar: 'الاستعاذة بالله من الشيطان',
      es: 'Me refugio en Alá del Satanás maldito',
      fr: 'Je cherche refuge auprès d’Allah contre Satan le lapidé',
    id: 'Aku berlindung kepada Allah dari setan yang terkutuk',
    bn: 'আমি আল্লাহর কাছে আশ্রয় চাই অভিশপ্ত শয়তান থেকে',
    fa: 'به خدا از شیطان رانده‌شده پناه می‌برم',
    ms: 'Aku berlindung kepada Allah daripada syaitan yang direjam',
    ur: 'میں اللہ کی پناہ چاہتا ہوں شیطان مردود سے',
    ru: 'Прибегаю к Аллаху от проклятого шайтана',
    sw: 'Najikinga kwa Allah dhidi ya shetani aliyelaaniwa',
    ps: 'زه الله ته پناه وړم د رټل شوي شیطان نه',
    },
  },
  {
    id: 'ilm',
    words: ['رَبِّ', 'زِدْنِي', 'عِلْمًا'],
    translit: 'Rabbi zidnī ʿilmā',
    meaning: {
      de: 'Mein Herr, mehre mein Wissen (Koran 20:114)',
      en: 'My Lord, increase me in knowledge (Quran 20:114)',
      tr: 'Rabbim, ilmimi artır (Kur’an 20:114)',
      ar: 'دعاء طلب العلم (طه ١١٤)',
      es: 'Señor mío, aumenta mi conocimiento (Corán 20:114)',
      fr: 'Seigneur, accrois mon savoir (Coran 20:114)',
    id: 'Ya Tuhanku, tambahkanlah kepadaku ilmu (Koran 20:114)',
    bn: 'হে আমার প্রতিপালক, আমার জ্ঞান বৃদ্ধি করে দাও (কুরআন ২০:১১৪)',
    fa: 'پروردگارا، بر دانش من بیفزای (قرآن ۲۰:۱۱۴)',
    ms: 'Ya Tuhanku, tambahkanlah ilmuku (Al-Quran 20:114)',
    ur: 'اے میرے رب، میرا علم بڑھا دے (قرآن 20:114)',
    ru: 'Господь мой, приумножь мои знания (Коран 20:114)',
    sw: 'Mola wangu, niongezee elimu (Qur\'an 20:114)',
    ps: 'زما ربه، ما ته زیات علم راکړه (قرآن 20:114)',
    },
  },
  {
    id: 'sabirin',
    words: ['إِنَّ', 'اللهَ', 'مَعَ', 'الصَّابِرِينَ'],
    translit: 'Innallāha maʿaṣ-ṣābirīn',
    meaning: {
      de: 'Allah ist mit den Geduldigen (Koran 2:153)',
      en: 'Allah is with the patient (Quran 2:153)',
      tr: 'Allah sabredenlerle beraberdir (Bakara 153)',
      ar: 'إن الله مع الصابرين (البقرة ١٥٣)',
      es: 'Alá está con los pacientes (Corán 2:153)',
      fr: 'Allah est avec les endurants (Coran 2:153)',
    id: 'Allah bersama orang-orang yang sabar (Koran 2:153)',
    bn: 'আল্লাহ ধৈর্যশীলদের সাথে আছেন (কুরআন ২:১৫৩)',
    fa: 'خداوند با صابران است (قرآن ۲:۱۵۳)',
    ms: 'Allah bersama orang-orang yang sabar (Al-Quran 2:153)',
    ur: 'اللہ صبر کرنے والوں کے ساتھ ہے (قرآن 2:153)',
    ru: 'Аллах с терпеливыми (Коран 2:153)',
    sw: 'Allah yu pamoja na wanaosubiri (Qur\'an 2:153)',
    ps: 'الله د صابرینو سره دی (قرآن 2:153)',
    },
  },
  {
    id: 'jazak',
    words: ['جَزَاكَ', 'اللهُ', 'خَيْرًا'],
    translit: 'Jazākallāhu khayrā',
    meaning: {
      de: 'Möge Allah dich mit Gutem belohnen',
      en: 'May Allah reward you with good',
      tr: 'Allah seni hayırla mükâfatlandırsın',
      ar: 'دعاء الشكر لمن أحسن إليك',
      es: 'Que Alá te recompense con el bien',
      fr: 'Qu’Allah te récompense en bien',
    id: 'Semoga Allah membalasmu dengan kebaikan',
    bn: 'আল্লাহ তোমাকে উত্তম প্রতিদান দিন',
    fa: 'خدا تو را به نیکی پاداش دهد',
    ms: 'Semoga Allah membalasmu dengan kebaikan',
    ur: 'اللہ تمہیں اچھا بدلہ دے',
    ru: 'Пусть Аллах вознаградит тебя добром',
    sw: 'Allah akulipe kwa wema',
    ps: 'الله دې تاته ښه بدله درکړي',
    },
  },
  {
    id: 'hawqala',
    words: ['لَا', 'حَوْلَ', 'وَلَا', 'قُوَّةَ', 'إِلَّا', 'بِاللهِ'],
    translit: 'Lā ḥawla wa-lā quwwata illā billāh',
    meaning: {
      de: 'Es gibt keine Macht und keine Kraft außer durch Allah',
      en: 'There is no power nor strength except through Allah',
      tr: 'Güç ve kuvvet ancak Allah iledir',
      ar: 'لا حول ولا قوة إلا بالله',
      es: 'No hay poder ni fuerza sino en Alá',
      fr: 'Il n’y a de force ni de puissance qu’en Allah',
    id: 'Tidak ada daya dan kekuatan kecuali dengan (pertolongan) Allah',
    bn: 'আল্লাহ ছাড়া কোনো শক্তি ও ক্ষমতা নেই',
    fa: 'هیچ نیرو و توانی جز به یاری خدا نیست',
    ms: 'Tiada daya dan kekuatan melainkan dengan (pertolongan) Allah',
    ur: 'کوئی طاقت اور قوت اللہ کے سوا نہیں',
    ru: 'Нет мощи и силы, кроме как через Аллаха',
    sw: 'Hakuna nguvu wala uwezo isipokuwa kwa Allah',
    ps: 'هیڅ زور او طاقت نشته پرته د الله له لارې نه',
    },
  },
  {
    id: 'istighfar',
    words: ['أَسْتَغْفِرُ', 'اللهَ', 'الْعَظِيمَ'],
    translit: 'Astaghfirullāhal-ʿaẓīm',
    meaning: {
      de: 'Ich bitte Allah, den Gewaltigen, um Vergebung',
      en: 'I seek forgiveness from Allah, the Magnificent',
      tr: 'Yüce Allah’tan bağışlanma dilerim',
      ar: 'طلب المغفرة من الله العظيم',
      es: 'Pido perdón a Alá, el Grandioso',
      fr: 'Je demande pardon à Allah l’Immense',
    id: 'Aku memohon ampun kepada Allah Yang Mahaagung',
    bn: 'আমি মহান আল্লাহর কাছে ক্ষমা প্রার্থনা করি',
    fa: 'از خداوند بزرگ طلب آمرزش می‌کنم',
    ms: 'Aku memohon ampun kepada Allah Yang Maha Agung',
    ur: 'میں اللہ عظیم سے بخشش مانگتا ہوں',
    ru: 'Прошу прощения у Аллаха Великого',
    sw: 'Namwomba msamaha Allah Mkuu',
    ps: 'زه له لوی الله نه بښنه غواړم',
    },
  },
  {
    id: 'hasbuna',
    words: ['حَسْبُنَا', 'اللهُ', 'وَنِعْمَ', 'الْوَكِيلُ'],
    translit: 'Ḥasbunallāhu wa-niʿmal-wakīl',
    meaning: {
      de: 'Allah genügt uns, und wie trefflich ist der Sachwalter (Koran 3:173)',
      en: 'Allah is sufficient for us, and He is the best Disposer of affairs (Quran 3:173)',
      tr: 'Allah bize yeter, O ne güzel vekildir (Âl-i İmrân 173)',
      ar: 'حسبنا الله ونعم الوكيل (آل عمران ١٧٣)',
      es: 'Alá nos basta, y qué excelente Protector (Corán 3:173)',
      fr: 'Allah nous suffit, quel excellent Garant (Coran 3:173)',
    id: 'Cukuplah Allah bagi kami, dan Dia adalah sebaik-baik Pelindung (Koran 3:173)',
    bn: 'আল্লাহই আমাদের জন্য যথেষ্ট, আর তিনিই উত্তম কার্যনির্বাহক (কুরআন ৩:১৭৩)',
    fa: 'خدا ما را کافی است و او بهترین کارساز است (قرآن ۳:۱۷۳)',
    ms: 'Cukuplah Allah bagi kami, dan Dialah sebaik-baik Pelindung (Al-Quran 3:173)',
    ur: 'ہمیں اللہ کافی ہے اور وہ بہترین کارساز ہے (قرآن 3:173)',
    ru: 'Достаточно нам Аллаха, и Он — лучший Попечитель (Коран 3:173)',
    sw: 'Allah anatutosha, na Yeye ni Mtegemewa bora (Qur\'an 3:173)',
    ps: 'الله زموږ لپاره بس دی، او هغه غوره کارساز دی (قرآن 3:173)',
    },
  },
  {
    id: 'istirja',
    words: ['إِنَّا', 'لِلَّهِ', 'وَإِنَّا', 'إِلَيْهِ', 'رَاجِعُونَ'],
    translit: 'Innā lillāhi wa-innā ilayhi rājiʿūn',
    meaning: {
      de: 'Wir gehören Allah, und zu Ihm kehren wir zurück (Koran 2:156)',
      en: 'To Allah we belong, and to Him we return (Quran 2:156)',
      tr: 'Biz Allah’a aitiz ve O’na döneceğiz (Bakara 156)',
      ar: 'إنا لله وإنا إليه راجعون (البقرة ١٥٦)',
      es: 'De Alá somos y a Él regresamos (Corán 2:156)',
      fr: 'Nous appartenons à Allah et vers Lui nous retournons (Coran 2:156)',
    id: 'Sesungguhnya kami milik Allah dan kepada-Nya kami kembali (Koran 2:156)',
    bn: 'আমরা আল্লাহরই এবং তাঁরই কাছে আমাদের প্রত্যাবর্তন (কুরআন ২:১৫৬)',
    fa: 'ما از آنِ خداییم و به‌سوی او بازمی‌گردیم (قرآن ۲:۱۵۶)',
    ms: 'Sesungguhnya kami milik Allah dan kepada-Nya kami kembali (Al-Quran 2:156)',
    ur: 'بے شک ہم اللہ ہی کے ہیں اور اسی کی طرف لوٹنے والے ہیں (قرآن 2:156)',
    ru: 'Поистине, мы принадлежим Аллаху, и к Нему мы вернёмся (Коран 2:156)',
    sw: 'Hakika sisi ni wa Allah, na Kwake tunarejea (Qur\'an 2:156)',
    ps: 'بېشکه موږ د الله یو، او هغه ته به ورګرځو (قرآن 2:156)',
    },
  },
  {
    id: 'salam',
    words: ['السَّلَامُ', 'عَلَيْكُمْ', 'وَرَحْمَةُ', 'اللهِ'],
    translit: 'As-salāmu ʿalaykum wa-raḥmatullāh',
    meaning: {
      de: 'Friede sei mit euch und Allahs Barmherzigkeit',
      en: 'Peace be upon you and the mercy of Allah',
      tr: 'Allah’ın selamı ve rahmeti üzerinize olsun',
      ar: 'تحية الإسلام',
      es: 'La paz sea con vosotros y la misericordia de Alá',
      fr: 'Que la paix et la miséricorde d’Allah soient sur vous',
    id: 'Semoga keselamatan dan rahmat Allah menyertaimu',
    bn: 'তোমার প্রতি শান্তি ও আল্লাহর রহমত বর্ষিত হোক',
    fa: 'سلام و رحمت خدا بر تو باد',
    ms: 'Semoga kesejahteraan dan rahmat Allah menyertaimu',
    ur: 'تم پر سلامتی اور اللہ کی رحمت ہو',
    ru: 'Мир вам и милость Аллаха',
    sw: 'Amani na rehema ya Allah ziwe juu yenu',
    ps: 'پر تاسو دې سلام او د الله رحمت وي',
    },
  },
  // Kurze Suren komplett, Vers für Vers — arabischer Text verifiziert gegen
  // api.alquran.cloud/v1/surah/{nr}/quran-uthmani (dieselbe Edition, die
  // features/quran/api.ts für den Mushaf-Reader nutzt). Basmala am Sure-Anfang
  // bewusst weggelassen (bereits eigener Eintrag 'basmala' oben, Verszählung
  // beginnt regulär erst danach — Ausnahme ist nur Al-Fatiha).
  {
    id: 'ikhlas-1',
    words: ['قُلْ', 'هُوَ', 'ٱللَّهُ', 'أَحَدٌ'],
    translit: 'Qul huwa Allāhu aḥad',
    meaning: {
      de: 'Sag: Er ist Allah, der Einzige (Koran 112:1)',
      en: 'Say: He is Allah, the One (Quran 112:1)',
      tr: 'De ki: O, Allah’tır, tektir (Kur’an 112:1)',
      ar: 'توحيد الله وأحديته (الإخلاص ١)',
      es: 'Di: Él es Alá, el Único (Corán 112:1)',
      fr: 'Dis: Il est Allah, l’Unique (Coran 112:1)',
    id: 'Katakanlah: Dialah Allah, Yang Maha Esa (Koran 112:1)',
    bn: 'বলো: তিনি আল্লাহ, একক (কুরআন ১১২:১)',
    fa: 'بگو: اوست خدای یگانه (قرآن ۱۱۲:۱)',
    ms: 'Katakanlah: Dialah Allah, Yang Maha Esa (Al-Quran 112:1)',
    ur: 'کہہ دو: وہ اللہ ایک ہے (قرآن 112:1)',
    ru: 'Скажи: Он — Аллах, Единый (Коран 112:1)',
    sw: 'Sema: Yeye ni Allah, Aliye Mmoja (Qur\'an 112:1)',
    ps: 'ووایه: هغه الله، یو یو دی (قرآن 112:1)',
    },
  },
  {
    id: 'ikhlas-2',
    words: ['ٱللَّهُ', 'ٱلصَّمَدُ'],
    translit: 'Allāhu ṣ-ṣamad',
    meaning: {
      de: 'Allah, der Absolute, von dem alles abhängt (Koran 112:2)',
      en: 'Allah, the Self-Sufficient, on whom all depend (Quran 112:2)',
      tr: 'Allah Samed’dir, her şey O’na muhtaçtır (Kur’an 112:2)',
      ar: 'الله الصمد الذي يُقصد في الحوائج (الإخلاص ٢)',
      es: 'Alá, el Absoluto, de quien todo depende (Corán 112:2)',
      fr: 'Allah, Le Seul à être imploré pour nos besoins (Coran 112:2)',
    id: 'Allah tempat bergantung segala sesuatu (Koran 112:2)',
    bn: 'আল্লাহ অমুখাপেক্ষী, যাঁর উপর সবকিছু নির্ভরশীল (কুরআন ১১২:২)',
    fa: 'خداوندی که همه به او نیازمندند (قرآن ۱۱۲:۲)',
    ms: 'Allah tempat bergantung segala sesuatu (Al-Quran 112:2)',
    ur: 'اللہ بےنیاز ہے، سب اسی کے محتاج ہیں (قرآن 112:2)',
    ru: 'Аллах, Самодостаточный, от Которого зависит всё (Коран 112:2)',
    sw: 'Allah Anayejitosheleza, ambaye vyote vinamtegemea (Qur\'an 112:2)',
    ps: 'الله بې نیازه، چې ټول ورته اړتیا لري (قرآن 112:2)',
    },
  },
  {
    id: 'ikhlas-3',
    words: ['لَمْ', 'يَلِدْ', 'وَلَمْ', 'يُولَدْ'],
    translit: 'Lam yalid wa-lam yūlad',
    meaning: {
      de: 'Er hat nicht gezeugt und ist nicht gezeugt worden (Koran 112:3)',
      en: 'He neither begets nor is born (Quran 112:3)',
      tr: 'O, doğurmamış ve doğurulmamıştır (Kur’an 112:3)',
      ar: 'الله لم يلد ولم يولد (الإخلاص ٣)',
      es: 'Él no engendra ni es engendrado (Corán 112:3)',
      fr: 'Il n’a jamais engendré, ni n’a été engendré (Coran 112:3)',
    id: 'Dia tidak beranak dan tidak pula diperanakkan (Koran 112:3)',
    bn: 'তিনি জন্মও দেননি, এবং তাঁকে জন্মও দেওয়া হয়নি (কুরআন ১১২:৩)',
    fa: 'نزاده و زاده نشده است (قرآن ۱۱۲:۳)',
    ms: 'Dia tidak beranak dan tidak pula diperanakkan (Al-Quran 112:3)',
    ur: 'نہ اس نے کسی کو جنا اور نہ وہ جنا گیا (قرآن 112:3)',
    ru: 'Он не рождает и не был рождён (Коран 112:3)',
    sw: 'Hakuzaa wala hakuzaliwa (Qur\'an 112:3)',
    ps: 'نه یې زیږولی او نه دی زیږول شوی (قرآن 112:3)',
    },
  },
  {
    id: 'ikhlas-4',
    words: ['وَلَمْ', 'يَكُن', 'لَّهُۥ', 'كُفُوًا', 'أَحَدٌۢ'],
    translit: 'Wa-lam yakun lahū kufuwan aḥad',
    meaning: {
      de: 'Und keiner ist Ihm ebenbürtig (Koran 112:4)',
      en: 'And there is none comparable to Him (Quran 112:4)',
      tr: 'Ve hiçbir şey O’na denk değildir (Kur’an 112:4)',
      ar: 'لا أحد يكافئ الله (الإخلاص ٤)',
      es: 'Y no hay nadie semejante a Él (Corán 112:4)',
      fr: 'Et nul n’est égal à Lui (Coran 112:4)',
    id: 'Dan tidak ada sesuatu pun yang setara dengan-Nya (Koran 112:4)',
    bn: 'এবং তাঁর সমতুল্য কেউ নেই (কুরআন ১১২:৪)',
    fa: 'و هیچ‌کس همتای او نیست (قرآن ۱۱۲:۴)',
    ms: 'Dan tiada sesuatu pun yang setara dengan-Nya (Al-Quran 112:4)',
    ur: 'اور اس کا کوئی ہمسر نہیں (قرآن 112:4)',
    ru: 'И нет никого равного Ему (Коран 112:4)',
    sw: 'Wala hakuna kilinganacho naye (Qur\'an 112:4)',
    ps: 'او هیڅوک ورسره سيال نشته (قرآن 112:4)',
    },
  },
  {
    id: 'falaq-1',
    words: ['قُلْ', 'أَعُوذُ', 'بِرَبِّ', 'ٱلْفَلَقِ'],
    translit: 'Qul aʿūdhu bi-rabbil-falaq',
    meaning: {
      de: 'Sag: Ich suche Zuflucht beim Herrn der Morgenröte (Koran 113:1)',
      en: 'Say: I seek refuge in the Lord of the daybreak (Quran 113:1)',
      tr: 'De ki: Sabahın Rabbine sığınırım (Kur’an 113:1)',
      ar: 'الاستعاذة برب الفلق (الفلق ١)',
      es: 'Di: Me refugio en el Señor del amanecer (Corán 113:1)',
      fr: 'Dis: Je cherche refuge auprès du Seigneur de l’aube naissante (Coran 113:1)',
    id: 'Katakanlah: Aku berlindung kepada Tuhan yang menguasai subuh (Koran 113:1)',
    bn: 'বলো: আমি আশ্রয় চাই ঊষার প্রভুর কাছে (কুরআন ১১৩:১)',
    fa: 'بگو: به پروردگار سپیده‌دم پناه می‌برم (قرآن ۱۱۳:۱)',
    ms: 'Katakanlah: Aku berlindung kepada Tuhan yang menguasai waktu subuh (Al-Quran 113:1)',
    ur: 'کہہ دو: میں صبح کے رب کی پناہ چاہتا ہوں (قرآن 113:1)',
    ru: 'Скажи: Прибегаю к Господу рассвета (Коран 113:1)',
    sw: 'Sema: Najikinga kwa Mola wa mapambazuko (Qur\'an 113:1)',
    ps: 'ووایه: زه د سهار رب ته پناه وړم (قرآن 113:1)',
    },
  },
  {
    id: 'falaq-2',
    words: ['مِن', 'شَرِّ', 'مَا', 'خَلَقَ'],
    translit: 'Min sharri mā khalaq',
    meaning: {
      de: 'Vor dem Übel dessen, was Er erschaffen hat (Koran 113:2)',
      en: 'From the evil of what He created (Quran 113:2)',
      tr: 'Yarattığı şeylerin şerrinden (Kur’an 113:2)',
      ar: 'الاستعاذة من شر المخلوقات (الفلق ٢)',
      es: 'Del mal de lo que ha creado (Corán 113:2)',
      fr: 'Contre le mal des êtres qu’Il a créés (Coran 113:2)',
    id: 'Dari kejahatan makhluk yang diciptakan-Nya (Koran 113:2)',
    bn: 'তাঁর সৃষ্ট সকল অনিষ্ট থেকে (কুরআন ১১৩:২)',
    fa: 'از شر آنچه آفریده است (قرآن ۱۱۳:۲)',
    ms: 'Daripada kejahatan makhluk yang diciptakan-Nya (Al-Quran 113:2)',
    ur: 'اس کی مخلوق کے شر سے (قرآن 113:2)',
    ru: 'От зла того, что Он сотворил (Коран 113:2)',
    sw: 'Dhidi ya shari ya alichokiumba (Qur\'an 113:2)',
    ps: 'د هغه له پیدا شویو شرونو نه (قرآن 113:2)',
    },
  },
  {
    id: 'falaq-3',
    words: ['وَمِن', 'شَرِّ', 'غَاسِقٍ', 'إِذَا', 'وَقَبَ'],
    translit: 'Wa-min sharri ghāsiqin idhā waqab',
    meaning: {
      de: 'Und vor dem Übel der Dunkelheit, wenn sie sich ausbreitet (Koran 113:3)',
      en: 'And from the evil of darkness when it settles (Quran 113:3)',
      tr: 'Karanlığı çöktüğünde gecenin şerrinden (Kur’an 113:3)',
      ar: 'الاستعاذة من شر الليل إذا أظلم (الفلق ٣)',
      es: 'Del mal de la oscuridad cuando se extiende (Corán 113:3)',
      fr: 'Contre le mal de l’obscurité quand elle s’installe (Coran 113:3)',
    id: 'Dan dari kejahatan malam apabila telah gelap gulita (Koran 113:3)',
    bn: 'এবং অন্ধকারের অনিষ্ট থেকে যখন তা ছেয়ে যায় (কুরআন ১১৩:৩)',
    fa: 'و از شر تاریکی چون فرارسد (قرآن ۱۱۳:۳)',
    ms: 'Dan daripada kejahatan malam apabila ia telah gelap-gelita (Al-Quran 113:3)',
    ur: 'اور اندھیرے کے شر سے جب وہ چھا جائے (قرآن 113:3)',
    ru: 'И от зла тьмы, когда она наступает (Коран 113:3)',
    sw: 'Na dhidi ya shari ya giza linapoingia (Qur\'an 113:3)',
    ps: 'او د تیارې له شر نه کله چې خپره شي (قرآن 113:3)',
    },
  },
  {
    id: 'falaq-4',
    words: ['وَمِن', 'شَرِّ', 'ٱلنَّفَّٰثَٰتِ', 'فِى', 'ٱلْعُقَدِ'],
    translit: 'Wa-min sharrin-naffāthāti fil-ʿuqad',
    meaning: {
      de: 'Und vor dem Übel der Knotenbläserinnen, der Zauberei (Koran 113:4)',
      en: 'And from the evil of the blowers in knots, sorcery (Quran 113:4)',
      tr: 'Düğümlere üfleyenlerin (büyücülerin) şerrinden (Kur’an 113:4)',
      ar: 'الاستعاذة من شر السحر (الفلق ٤)',
      es: 'Del mal de las que soplan en los nudos, la hechicería (Corán 113:4)',
      fr: 'Contre le mal des souffleuses sur les nœuds, la sorcellerie (Coran 113:4)',
    id: 'Dan dari kejahatan wanita-wanita tukang sihir yang meniup pada buhul-buhul (Koran 113:4)',
    bn: 'এবং গিঁটে ফুৎকারদাত্রীদের অনিষ্ট থেকে, জাদু থেকে (কুরআন ১১৩:৪)',
    fa: 'و از شر افسونگرانِ دمنده در گره‌ها، جادو (قرآن ۱۱۳:۴)',
    ms: 'Dan daripada kejahatan tukang-tukang sihir yang meniup pada buhul-buhul (Al-Quran 113:4)',
    ur: 'اور گرہوں میں پھونکنے والیوں کے شر سے، جادو سے (قرآن 113:4)',
    ru: 'И от зла дующих на узлы, колдовства (Коран 113:4)',
    sw: 'Na dhidi ya shari ya wapulizao vifundo, uchawi (Qur\'an 113:4)',
    ps: 'او د هغو ښځو له شر نه چې په غوټو پوکی کوي، له جادو نه (قرآن 113:4)',
    },
  },
  {
    id: 'falaq-5',
    words: ['وَمِن', 'شَرِّ', 'حَاسِدٍ', 'إِذَا', 'حَسَدَ'],
    translit: 'Wa-min sharri ḥāsidin idhā ḥasad',
    meaning: {
      de: 'Und vor dem Übel eines Neiders, wenn er neidet (Koran 113:5)',
      en: 'And from the evil of an envier when he envies (Quran 113:5)',
      tr: 'Kıskandığı zaman kıskanç kişinin şerrinden (Kur’an 113:5)',
      ar: 'الاستعاذة من شر الحاسد (الفلق ٥)',
      es: 'Del mal del envidioso cuando envidia (Corán 113:5)',
      fr: 'Contre le mal de l’envieux quand il envie (Coran 113:5)',
    id: 'Dan dari kejahatan orang yang dengki apabila ia dengki (Koran 113:5)',
    bn: 'এবং হিংসুকের অনিষ্ট থেকে যখন সে হিংসা করে (কুরআন ১১৩:৫)',
    fa: 'و از شر حسود، آنگاه که حسد ورزد (قرآن ۱۱۳:۵)',
    ms: 'Dan daripada kejahatan orang yang dengki apabila ia dengki (Al-Quran 113:5)',
    ur: 'اور حسد کرنے والے کے شر سے جب وہ حسد کرے (قرآن 113:5)',
    ru: 'И от зла завистника, когда он завидует (Коран 113:5)',
    sw: 'Na dhidi ya shari ya mwenye husuda anapohusudu (Qur\'an 113:5)',
    ps: 'او د حسود کس له شر نه کله چې حسد کوي (قرآن 113:5)',
    },
  },
  {
    id: 'nas-1',
    words: ['قُلْ', 'أَعُوذُ', 'بِرَبِّ', 'ٱلنَّاسِ'],
    translit: 'Qul aʿūdhu bi-rabbin-nās',
    meaning: {
      de: 'Sag: Ich suche Zuflucht beim Herrn der Menschen (Koran 114:1)',
      en: 'Say: I seek refuge in the Lord of mankind (Quran 114:1)',
      tr: 'De ki: İnsanların Rabbine sığınırım (Kur’an 114:1)',
      ar: 'الاستعاذة برب الناس (الناس ١)',
      es: 'Di: Me refugio en el Señor de los hombres (Corán 114:1)',
      fr: 'Dis: Je cherche refuge auprès du Seigneur des hommes (Coran 114:1)',
    id: 'Katakanlah: Aku berlindung kepada Tuhan manusia (Koran 114:1)',
    bn: 'বলো: আমি আশ্রয় চাই মানুষের প্রভুর কাছে (কুরআন ১১৪:১)',
    fa: 'بگو: به پروردگار مردم پناه می‌برم (قرآن ۱۱۴:۱)',
    ms: 'Katakanlah: Aku berlindung kepada Tuhan sekalian manusia (Al-Quran 114:1)',
    ur: 'کہہ دو: میں لوگوں کے رب کی پناہ چاہتا ہوں (قرآن 114:1)',
    ru: 'Скажи: Прибегаю к Господу людей (Коран 114:1)',
    sw: 'Sema: Najikinga kwa Mola wa watu (Qur\'an 114:1)',
    ps: 'ووایه: زه د خلکو رب ته پناه وړم (قرآن 114:1)',
    },
  },
  {
    id: 'nas-2',
    words: ['مَلِكِ', 'ٱلنَّاسِ'],
    translit: 'Maliki n-nās',
    meaning: {
      de: 'Dem König der Menschen (Koran 114:2)',
      en: 'The Sovereign of mankind (Quran 114:2)',
      tr: 'İnsanların Melik’ine, Hükümdarına (Kur’an 114:2)',
      ar: 'الله ملك الناس (الناس ٢)',
      es: 'El Rey de los hombres (Corán 114:2)',
      fr: 'Le Souverain des hommes (Coran 114:2)',
    id: 'Raja manusia (Koran 114:2)',
    bn: 'মানুষের অধিপতি (কুরআন ১১৪:২)',
    fa: 'پادشاه مردم (قرآن ۱۱۴:۲)',
    ms: 'Raja manusia (Al-Quran 114:2)',
    ur: 'لوگوں کے بادشاہ (قرآن 114:2)',
    ru: 'Владыке людей (Коран 114:2)',
    sw: 'Mfalme wa watu (Qur\'an 114:2)',
    ps: 'د خلکو باچا (قرآن 114:2)',
    },
  },
  {
    id: 'nas-3',
    words: ['إِلَٰهِ', 'ٱلنَّاسِ'],
    translit: 'Ilāhi n-nās',
    meaning: {
      de: 'Dem Gott der Menschen (Koran 114:3)',
      en: 'The God of mankind (Quran 114:3)',
      tr: 'İnsanların İlâh’ına (Kur’an 114:3)',
      ar: 'الله إله الناس (الناس ٣)',
      es: 'El Dios de los hombres (Corán 114:3)',
      fr: 'Le Dieu des hommes (Coran 114:3)',
    id: 'Sesembahan manusia (Koran 114:3)',
    bn: 'মানুষের উপাস্য (কুরআন ১১৪:৩)',
    fa: 'معبود مردم (قرآن ۱۱۴:۳)',
    ms: 'Sembahan manusia (Al-Quran 114:3)',
    ur: 'لوگوں کے معبود (قرآن 114:3)',
    ru: 'Богу людей (Коран 114:3)',
    sw: 'Mola wa watu (Qur\'an 114:3)',
    ps: 'د خلکو معبود (قرآن 114:3)',
    },
  },
  {
    id: 'nas-4',
    words: ['مِن', 'شَرِّ', 'ٱلْوَسْوَاسِ', 'ٱلْخَنَّاسِ'],
    translit: 'Min sharril-waswāsil-khannās',
    meaning: {
      de: 'Vor dem Übel des heimlich einflüsternden Versuchers (Koran 114:4)',
      en: 'From the evil of the retreating whisperer (Quran 114:4)',
      tr: 'Sinsi vesvesecinin şerrinden (Kur’an 114:4)',
      ar: 'الاستعاذة من شر الوسواس الخناس (الناس ٤)',
      es: 'Del mal del susurrador furtivo (Corán 114:4)',
      fr: 'Contre le mal du mauvais conseiller, furtif (Coran 114:4)',
    id: 'Dari kejahatan (bisikan) setan yang bersembunyi (Koran 114:4)',
    bn: 'গোপনে কুমন্ত্রণাদাতার অনিষ্ট থেকে (কুরআন ১১৪:৪)',
    fa: 'از شر وسوسه‌گر پنهان‌شونده (قرآن ۱۱۴:۴)',
    ms: 'Daripada kejahatan (bisikan) syaitan yang bersembunyi (Al-Quran 114:4)',
    ur: 'چھپ جانے والے وسوسہ انداز کے شر سے (قرآن 114:4)',
    ru: 'От зла скрывающегося искусителя (Коран 114:4)',
    sw: 'Dhidi ya shari ya mnong\'onezaji anayejificha (Qur\'an 114:4)',
    ps: 'د پټیدونکي وسوسه کوونکي له شر نه (قرآن 114:4)',
    },
  },
  {
    id: 'nas-5',
    words: ['ٱلَّذِى', 'يُوَسْوِسُ', 'فِى', 'صُدُورِ', 'ٱلنَّاسِ'],
    translit: 'Alladhī yuwaswisu fī ṣudūrin-nās',
    meaning: {
      de: 'Der den Menschen Einflüsterungen in die Brust eingibt (Koran 114:5)',
      en: 'Who whispers into the breasts of mankind (Quran 114:5)',
      tr: 'İnsanların göğüslerine vesvese veren (Kur’an 114:5)',
      ar: 'الشيطان يوسوس في صدور الناس (الناس ٥)',
      es: 'Que susurra en los pechos de los hombres (Corán 114:5)',
      fr: 'Qui souffle le mal dans les poitrines des hommes (Coran 114:5)',
    id: 'Yang membisikkan (kejahatan) ke dalam dada manusia (Koran 114:5)',
    bn: 'যে মানুষের অন্তরে কুমন্ত্রণা দেয় (কুরআন ১১৪:৫)',
    fa: 'که در سینه‌های مردم وسوسه می‌کند (قرآن ۱۱۴:۵)',
    ms: 'Yang membisikkan (kejahatan) ke dalam dada manusia (Al-Quran 114:5)',
    ur: 'جو لوگوں کے سینوں میں وسوسہ ڈالتا ہے (قرآن 114:5)',
    ru: 'Который наущает в груди людей (Коран 114:5)',
    sw: 'Anayenong\'oneza vifuani mwa watu (Qur\'an 114:5)',
    ps: 'چې د خلکو په سینو کې وسوسه اچوي (قرآن 114:5)',
    },
  },
  {
    id: 'nas-6',
    words: ['مِنَ', 'ٱلْجِنَّةِ', 'وَٱلنَّاسِ'],
    translit: 'Minal-jinnati wan-nās',
    meaning: {
      de: 'Von den Dschinn und den Menschen (Koran 114:6)',
      en: 'From among the jinn and mankind (Quran 114:6)',
      tr: 'Cinlerden ve insanlardan (Kur’an 114:6)',
      ar: 'الوسواس من الجن والإنس (الناس ٦)',
      es: 'De entre los genios y los hombres (Corán 114:6)',
      fr: 'Qu’il soit des djinns ou des hommes (Coran 114:6)',
    id: 'Dari (golongan) jin dan manusia (Koran 114:6)',
    bn: 'জিন ও মানুষের মধ্য থেকে (কুরআন ১১৪:৬)',
    fa: 'از جنیان و آدمیان (قرآن ۱۱۴:۶)',
    ms: 'Daripada (golongan) jin dan manusia (Al-Quran 114:6)',
    ur: 'خواہ جنوں میں سے ہو یا انسانوں میں سے (قرآن 114:6)',
    ru: 'Из числа джиннов и людей (Коран 114:6)',
    sw: 'Miongoni mwa majini na watu (Qur\'an 114:6)',
    ps: 'د پېریانو او انسانانو څخه (قرآن 114:6)',
    },
  },
  {
    id: 'kawthar-1',
    words: ['إِنَّآ', 'أَعْطَيْنَٰكَ', 'ٱلْكَوْثَرَ'],
    translit: 'Innā aʿṭaynāka l-kawthar',
    meaning: {
      de: 'Wahrlich, Wir haben dir den Kawthar (Überfluss) gegeben (Koran 108:1)',
      en: 'Indeed, We have granted you al-Kawthar, abundance (Quran 108:1)',
      tr: 'Şüphesiz sana Kevser’i (bolluğu) verdik (Kur’an 108:1)',
      ar: 'الله أعطى النبي الكوثر (الكوثر ١)',
      es: 'En verdad, te hemos dado el Kawzar, la abundancia (Corán 108:1)',
      fr: 'Nous t’avons certes accordé l’Abondance, al-Kawthar (Coran 108:1)',
    id: 'Sesungguhnya Kami telah memberimu Kautsar, kenikmatan yang berlimpah (Koran 108:1)',
    bn: 'নিশ্চয়ই আমি তোমাকে কাউসার, প্রাচুর্য দান করেছি (কুরআন ১০৮:১)',
    fa: 'همانا ما به تو کوثر، فراوانی بخشیدیم (قرآن ۱۰۸:۱)',
    ms: 'Sesungguhnya Kami telah mengurniakanmu Kausar, kenikmatan yang berlimpah (Al-Quran 108:1)',
    ur: 'بے شک ہم نے تمہیں کوثر، بےشمار خیر عطا کی (قرآن 108:1)',
    ru: 'Поистине, Мы даровали тебе аль-Каусар, изобилие (Коран 108:1)',
    sw: 'Hakika Tumekupa al-Kawthar, wingi wa kheri (Qur\'an 108:1)',
    ps: 'یقینا موږ تاته کوثر، ډیره ښیګڼه درکړه (قرآن 108:1)',
    },
  },
  {
    id: 'kawthar-2',
    words: ['فَصَلِّ', 'لِرَبِّكَ', 'وَٱنْحَرْ'],
    translit: 'Fa-ṣalli li-rabbika wanḥar',
    meaning: {
      de: 'So bete zu deinem Herrn und opfere (Koran 108:2)',
      en: 'So pray to your Lord and sacrifice (Quran 108:2)',
      tr: 'Öyleyse Rabbin için namaz kıl ve kurban kes (Kur’an 108:2)',
      ar: 'أمر بالصلاة والنحر شكرا لله (الكوثر ٢)',
      es: 'Ora, pues, a tu Señor y sacrifica (Corán 108:2)',
      fr: 'Accomplis la Salât pour ton Seigneur et sacrifie (Coran 108:2)',
    id: 'Maka dirikanlah salat karena Tuhanmu dan berkurbanlah (Koran 108:2)',
    bn: 'সুতরাং তোমার প্রতিপালকের উদ্দেশ্যে সালাত আদায় করো এবং কুরবানি দাও (কুরআন ১০৮:২)',
    fa: 'پس برای پروردگارت نماز بگزار و قربانی کن (قرآن ۱۰۸:۲)',
    ms: 'Maka dirikanlah solat kerana Tuhanmu dan berkorbanlah (Al-Quran 108:2)',
    ur: 'پس اپنے رب کے لیے نماز پڑھو اور قربانی کرو (قرآن 108:2)',
    ru: 'Так молись же своему Господу и приноси жертву (Коран 108:2)',
    sw: 'Basi swali kwa ajili ya Mola wako na uchinje (Qur\'an 108:2)',
    ps: 'نو خپل رب ته لمونځ وکړه او قرباني وکړه (قرآن 108:2)',
    },
  },
  {
    id: 'kawthar-3',
    words: ['إِنَّ', 'شَانِئَكَ', 'هُوَ', 'ٱلْأَبْتَرُ'],
    translit: 'Inna shāniʾaka huwa l-abtar',
    meaning: {
      de: 'Wahrlich, dein Hasser ist der Abgeschnittene, ohne Nachkommen (Koran 108:3)',
      en: 'Indeed, your enemy is the one cut off (Quran 108:3)',
      tr: 'Şüphesiz sana buğzeden, soyu kesik olandır (Kur’an 108:3)',
      ar: 'من يبغض النبي هو المنقطع الذكر (الكوثر ٣)',
      es: 'En verdad, quien te odia es el privado de posteridad (Corán 108:3)',
      fr: 'Celui qui te hait sera certes sans postérité (Coran 108:3)',
    id: 'Sesungguhnya orang yang membencimu, dialah yang terputus (Koran 108:3)',
    bn: 'নিশ্চয়ই তোমার শত্রুই বংশচ্ছিন্ন (কুরআন ১০৮:৩)',
    fa: 'همانا دشمن تو، خود بریده‌نسل است (قرآن ۱۰۸:۳)',
    ms: 'Sesungguhnya orang yang membencimu, dialah yang terputus (Al-Quran 108:3)',
    ur: 'بے شک تمہارا دشمن ہی بےنام و نشان رہ جانے والا ہے (قرآن 108:3)',
    ru: 'Поистине, твой враг — он и есть отсечённый от блага (Коран 108:3)',
    sw: 'Hakika adui yako ndiye aliyekatiliwa mbali (Qur\'an 108:3)',
    ps: 'یقینا ستا دښمن هماغه پرې شوی دی (قرآن 108:3)',
    },
  },
  {
    id: 'asr-1',
    words: ['وَٱلْعَصْرِ', 'إِنَّ', 'ٱلْإِنسَٰنَ', 'لَفِى', 'خُسْرٍ'],
    translit: 'Wal-ʿaṣr, innal-insāna lafī khusr',
    meaning: {
      de: 'Bei der Zeit! Wahrlich, der Mensch ist im Verlust (Koran 103:1-2)',
      en: 'By time! Indeed, mankind is in loss (Quran 103:1-2)',
      tr: 'Asra andolsun, insan gerçekten hüsrandadır (Kur’an 103:1-2)',
      ar: 'قسم بالعصر أن الإنسان في خسران (العصر ١-٢)',
      es: '¡Por el tiempo! El hombre está en pérdida (Corán 103:1-2)',
      fr: 'Par le Temps! L’homme est certes en perdition (Coran 103:1-2)',
    id: 'Demi masa! Sesungguhnya manusia benar-benar berada dalam kerugian (Koran 103:1-2)',
    bn: 'সময়ের শপথ! নিশ্চয়ই মানুষ ক্ষতির মধ্যে রয়েছে (কুরআন ১০৩:১-২)',
    fa: 'سوگند به عصر! که انسان در زیان است (قرآن ۱۰۳:۱-۲)',
    ms: 'Demi masa! Sesungguhnya manusia benar-benar berada dalam kerugian (Al-Quran 103:1-2)',
    ur: 'زمانے کی قسم! بے شک انسان خسارے میں ہے (قرآن 103:1-2)',
    ru: 'Клянусь временем! Поистине, человек в убытке (Коран 103:1-2)',
    sw: 'Naapa kwa wakati! Hakika mwanadamu yumo hasarani (Qur\'an 103:1-2)',
    ps: 'قسم په وخت! یقینا انسان په تاوان کې دی (قرآن 103:1-2)',
    },
  },
  {
    id: 'asr-2',
    words: [
      'إِلَّا',
      'ٱلَّذِينَ',
      'ءَامَنُوا۟',
      'وَعَمِلُوا۟',
      'ٱلصَّٰلِحَٰتِ',
      'وَتَوَاصَوْا۟',
      'بِٱلْحَقِّ',
      'وَتَوَاصَوْا۟',
      'بِٱلصَّبْرِ',
    ],
    translit: 'Illalladhīna āmanū wa-ʿamiluṣ-ṣāliḥāti wa-tawāṣaw bil-ḥaqqi wa-tawāṣaw biṣ-ṣabr',
    meaning: {
      de: 'Außer denen, die glauben, Gutes tun und einander zu Wahrheit und Geduld ermahnen (Koran 103:3)',
      en: 'Except those who believe, do good deeds, and enjoin truth and enjoin patience (Quran 103:3)',
      tr: 'Ancak iman edip salih ameller işleyen, hakkı ve sabrı tavsiye edenler hariç (Kur’an 103:3)',
      ar: 'إلا المؤمنون الصالحون المتواصون بالحق والصبر (العصر ٣)',
      es: 'Excepto quienes creen, obran bien y se recomiendan la verdad y la paciencia (Corán 103:3)',
      fr: 'Sauf ceux qui croient, font de bonnes œuvres et se recommandent la vérité et la patience (Coran 103:3)',
    id: 'Kecuali orang-orang yang beriman, beramal saleh, dan saling menasihati dalam kebenaran dan kesabaran (Koran 103:3)',
    bn: 'তবে তারা ব্যতীত যারা ঈমান আনে, সৎকর্ম করে, এবং পরস্পরকে সত্যের ও ধৈর্যের উপদেশ দেয় (কুরআন ১০৩:৩)',
    fa: 'مگر کسانی که ایمان آوردند و کارهای شایسته کردند و یکدیگر را به حق و به شکیبایی سفارش کردند (قرآن ۱۰۳:۳)',
    ms: 'Kecuali orang-orang yang beriman, beramal soleh, dan berpesan-pesan dengan kebenaran serta kesabaran (Al-Quran 103:3)',
    ur: 'سوائے ان کے جو ایمان لائے، نیک عمل کیے، اور آپس میں حق کی اور صبر کی نصیحت کرتے رہے (قرآن 103:3)',
    ru: 'Кроме тех, которые уверовали, совершали праведные деяния и заповедали друг другу истину и заповедали друг другу терпение (Коран 103:3)',
    sw: 'Isipokuwa wale walioamini, wakatenda mema, na wakausiana kwa haki na wakausiana kwa subira (Qur\'an 103:3)',
    ps: 'پرته له هغو چې ایمان یې راوړی، نیک عمل یې کړی، او یو بل ته یې د حق او صبر سپارښتنه کړې (قرآن 103:3)',
    },
  },
];

export const PUZZLE_ROUNDS = 5;

export interface PuzzleRound {
  phrase: PuzzlePhrase;
  /** Gemischte Wort-Indizes — Indizes statt Strings wegen doppelter Wörter. */
  shuffled: number[];
}

/** Mischen, bis die Reihenfolge nicht schon die Lösung ist (max. 10 Versuche). */
function shuffledOrder(count: number, rand: Rand): number[] {
  const base = Array.from({ length: count }, (_, i) => i);
  for (let i = 0; i < 10; i++) {
    const mixed = shuffle(base, rand);
    if (mixed.some((v, idx) => v !== idx)) return mixed;
  }
  return [...base].reverse();
}

export function buildPuzzleRun(rand: Rand = Math.random): PuzzleRound[] {
  return shuffle(PUZZLE_PHRASES, rand)
    .slice(0, PUZZLE_ROUNDS)
    .map((phrase) => ({ phrase, shuffled: shuffledOrder(phrase.words.length, rand) }));
}
